title: StepsToSucces
description: "Top public-policy ideas & case studies. (ES/EN)"

# 🔹 No usamos remote_theme porque queremos nuestro layout propio
theme: null

# Colecciones
collections:
  cases:
    output: true
    permalink: /cases/:name/

# Plugins útiles
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# URL y dominio
url: "https://www.stepstosucces.com"
baseurl: ""   # déjalo vacío porque usas dominio con CNAME

# Enlaces rápidos opcionales en top-right (si los usas en layout)
aux_links:
  "GitHub":
    - "https://github.com/EmilioT2003/stepstosucces"
