title: StepsToSucces
description: Top public-policy ideas & case studies. (ES/EN)
remote_theme: just-the-docs/just-the-docs
search_enabled: true
logo: /assets/logo.svg

# Collections
collections:
  cases:
    output: true
    permalink: /cases/:name/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://www.stepstosucces.com"
logo: /assets/logo.svg

# Enlaces rápidos opcionales en top-right
aux_links:
  "GitHub":
    - "https://github.com/EmilioT2003/stepstosucces"

# Activar CSS personalizado
just_the_docs:
  custom_css: assets/css/custom.css
